= XML validation policy

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-xml-validation/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/gravitee-policy-xml-validation/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Phase

[cols="2*", options="header"]
|===
^|onRequestContent
^|onResponseContent

^.^| X
^.^|

|===

== Description

You can use the `xml-validation` policy to validate XML using an XSD schema. This policy uses `javax.xml`.
A 400 BAD REQUEST error is received with a custom error message body wwith a custom error message body hen validation fails.
Injects processing report messages into request metrics for analytics.


== Configuration

|===
|Property |Required |Description |Type| Default

.^|errorMessage
^.^|
|Custom error message in XML format. Spel is allowed.
^.^|string
|validation/internal

.^|xsdSchema
^.^|X
|Xsd schema.
^.^|string
|

|===

== Error

=== HTTP status code

|===
|Code |Message

.^| ```400```
| Applies to:

* Invalid payload

* Invalid XSD schema

* Invalid error message XML format

|===
